### ISSUE TITLE
Any way to make this all a chrome bookmark?

### ISSUE THREAD

**Issue by REALDarianDev** [ArjhanToteck/iReady-Overload#11]
Hey, I've been using this for a while, and in my school's laptops, dev mode is off. I cannot use the extension, but I can add bookmarks. I made the lesson skipper to a bookmark, can you make the GUI a bookmark? Thanks!

**Comment by ArjhanToteck** [comment]
I should be able to do that pretty soon.

**Comment by REALDarianDev** [comment]
Thank you so much!
I made the lesson skipper a bookmark, but my school deleted all chrome bookmarks, and i lost it. I also want to use the diagnostic hack but i cant convert that, nor i can convert the GUI. Thanks again!

**Comment by ArjhanToteck** [comment]
I made a [bookmarklet](https://github.com/ArjhanToteck/iReady-Overload/blob/main/bookmarklet.txt) that opens the same iReady Overload panel the chrome extension does. The only thing it can't do is the Lesson Viewer feature, because of the way it works, which won't be a problem for what you intend to use it for.
